name: My Test workflow

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '* * * * *'
  
    
jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - run: echo "Hello You! Nice to meet you"
